name = "cTab Web Companion"
prefix = "ctab_web"
mainprefix = "z"
author = "[GRP9] NiklasKy"

[version]
major = 1
minor = 0
patch = 1
git_hash = 0

[hemtt.check]
pdrive = "disallow"

[hemtt.build]
pdrive = "disallow"
